### ISSUE TITLE
How do I use an existing MessageType?

### ISSUE THREAD

**Issue by hntd187** [mjakubowski84/parquet4s#107]
I already have a `MessageType` that I'd like to use to write parquet files, most of the actual message type schema setting is private, is there a way to do this I'm missing?

**Comment by mjakubowski84** [comment]
Hi!

I do not know your use case but I am not sure if using own MessageType is a good idea. You still have to provide a case class to write data. Library will resolve the schema on its own. If your custom MessageType differs in field types from what Parquet4S generates then it will just break. Unless you see that there is something wrong with generated schema I recommend using what is provided by the lib. Otherwise please create an issue - let's fix it!
If your case is that you need something really specific to your use case you may try implementing your own instance of type class of `ParquetSchemaResolver` that will take field definitions out from your MessageType. It should be very simple. Just place it in a proper implicit scope. I hope it will work then!

**Comment by hntd187** [comment]
I was specifically looking for a way I could have a parquet schema from a file and be able to write to that without having to rely on avro or thrift. Since you can parse the message schema using parquet's library I already had a message type to use, hopefully that makes sense. I'll give the parquet schema resolver impl a try and see if that does it.

**Comment by mjakubowski84** [comment]
Maybe that will explain you - this lib replaced avro or thrift by a case
class. You do not use massage type here.

czw., 26 wrz 2019, 20:41 użytkownik Stephen Carman <notifications@github.com>
napisał:

**Comment by hntd187** [comment]
I see, okay I appreciate your very fast response, I'm going to have to write my own implementation of this it would seem, but this library is awesome and I plan to definitely use it in the future when I have concrete case classes to use. thanks!
