### ISSUE TITLE
[Question] Can you add an example of reading Parquet file with a custom type

### ISSUE THREAD

**Issue by psilos** [mjakubowski84/parquet4s#108]
At the moment the example is focusing on writing data on Parquet format, 
could you add an example about reading data from Parquet format? It currently needs an implicit Decoder to be manually added, is there an easy way to do so?

**Comment by mjakubowski84** [comment]
Hi, the same example applies, but, as readme says, if you do not need to write your custom type then you don't have to provide additional implementation of ParquetSchemaResolver.

**Comment by sorhus** [comment]
I also understand the read example to be incomplete. I get something similar to 
`could not find implicit value for parameter reader: com.github.mjakubowski84.parquet4s.ParquetReader[User]`

Is there some import missing?

**Comment by mjakubowski84** [comment]
No, there's no need to import anything. The example provided is all that you need to read regular case class.  You can check tests, e.g. it-tests for plenty of examples.

If you use custom types in your case class then you have to provide own implicit codec - as it is mentioned in README.

If your code doesn't compile then it mean that you are missing either implicit codec for your custom type. It maybe also so that you use reader with generics and you didn't mark your function to use reader's type class.

What is truly missing in this project is a documented list of types that are supported out of the box, so that devs do not have to dig though the code to find it out. I plan to add it with next release.

**Comment by mjakubowski84** [comment]
@sorhus `Seq` is supported, too! https://github.com/mjakubowski84/parquet4s/blob/master/core/src/main/scala/com/github/mjakubowski84/parquet4s/CollectionTransformer.scala
it is tested, too!

Did you use "regular" Seq or was it some explicit mutable or immutable one?
You worried me! If your Seq is not working then maybe it would best to create an issue to support all versions of Scala collections.

**Comment by sorhus** [comment]
Ah, you are right of course. It was actually a case of a `scala.collection.Map` -> `Map`.

Is this something you think should be supported?

Thanks for the lib by the way, working great now!

**Comment by mjakubowski84** [comment]
Maps are supported, too :)
Here's the list of of all tested cases: https://github.com/mjakubowski84/parquet4s/blob/master/core/src/it/scala/com/github/mjakubowski84/parquet4s/CompatibilityTestCases.scala

**Comment by sorhus** [comment]
To clarify, it works with `case classA(m: Map[String, String])`, but not with `case class B(m: scala.collection.Map[String,String])`

i.e. not with the mutable version.

**Comment by mjakubowski84** [comment]
Thanks! As I thought. Mutable collection would not work. I will create an issue to address it.

**Comment by mjakubowski84** [comment]
@psilos Did you manage to solve your issue? Do you need help or shall we close the issue?

**Comment by psilos** [comment]
Closing down as it was a question mainly, but yes the docs were referring to a custom type `ParquetReader[User]` and wanted to find out how is the Decoder specified for this type for a similar use case.
