### ISSUE TITLE
In-place update of parquet records

### ISSUE THREAD

**Issue by mac01021** [mjakubowski84/parquet4s#133]
Hi!  It's me again!

I'm still working on the same use case I mentioned in #132, performing ETL on parquet files with unknown schema and producing new parquet files containing a transformed version of the original content.

How would you feel if I sent you a PR that exposes the ability to do in-place updates of the `mutable.ArrayBuffer`s and `mutable.Map`s inside of `RowParquetRecords`, `ListParquetRecords` and `MapParquetRecords`?

That way, if I need to encrypt column 57 of my parquet file, I don't need to copy the other 400 fields in order to do it.

If you're not comfortable with the mutation, I can simply make them all `Iterable` the way I did for `RowParquetRecord` in my previous PR.   But mutation, as you know, facilitates better performance.

Thanks!

**Comment by mjakubowski84** [comment]
Sure, you can do it!
`*ParquetRecord` already has `add` function, some has others. I understand that you want to add `set` function that can modify collection in efficient way.
Please keep in mind that all implementations of ParquetRecord were designed rather for internal use. You can notice ugly castings, etc. Those closes may undergo some changes in API and internals in order to make them more suitable for public usage (as yours) as well as to make them more efficient. E.g. ArrayBuffer seems to be good enough but especially since Scala 2.13 Vector and/or making ParquetRecord immutable may be a better choice.

**Comment by mac01021** [comment]
It would probably look something like #134.

**Comment by mac01021** [comment]
I had originally hoped, without thinking too much about it, that a `RowParquetRecord` coming from the reader would have `NullValue`s in columns where no value is set.

For example, my parquet file has 991 optional columns and a typical row has only about 300 nonnull columns.  I would like to be able to inspect the schema once, before reading in the file, to find the numeric index of the column I am interested in.  And then for every row directly access that numeric index rather than searching for the value by way of a hundred string comparisons.

I don't fully understand your library's internals, or the parquet ReadSupport abstraction yet.  But if there is an easy way to make this happen, it may be worth considering.

If I understand correctly, adding those `NullValue`s will not have any effect on the writer, because it already has a case for ignoring nulls?

**Comment by mjakubowski84** [comment]
Regarding NullValue. 
Parquet works that way that it does is saves no data for the column that is null. `ReadSupport` is an abstract class coming from Parquet that you have to implement when writing your own reader. And there's no action fired when reading null column. So, if value for column is missing then you have no data in RowParquetRecord stored. It is good as it saves memory.
I introduced NullValue in order to represent missing (null or None) in the context of schema defined by case class. It is helpful especially when writing data. But is also used by encoder: https://github.com/mjakubowski84/parquet4s/blob/master/core/src/main/scala/com/github/mjakubowski84/parquet4s/ParquetRecordDecoder.scala#L53. And I guess that this is what you want more or less. You can see that here content of RowParquetRecord is converted to Map and then the map is used for lookup. You must admit that this is not an optimal way. Thanks to your changes we can make it better.:

1) Using iterator we can make lookups 2x faster (in context of whole record). 
2) There's also a possibility to store name -> column index mapping in another collection but that must be updated on every record mutation. I am not sure if that is worth the effort.
3) We can move lookup by name to RowParquetRecord and create a function that returns NullValue when there's no data stored for given name.

**Comment by mjakubowski84** [comment]
I'm going to play a little with your PR and check what can be done :)

**Comment by mac01021** [comment]
Thanks for taking a look!

To be clear, I don't really care whether or not there are slots in memory
full if NullValue.  I just want to be able to read in the the rows and
update a specific column in each row as efficiently as possible.

I think for my use case that may mean that RowParquetRecord would best use
a Map or OrderedMap instead of an ArrayBuffer?  But that might slow down
your typical use case where the row gets mapped onto a case class...

**Comment by mac01021** [comment]
Now that I think about it, probably the most efficient solution is to
continue using a plain ArrayBuffer.

Then in userland I can take a single pass over the sequence to build a map
indexing only the specific fields I'm interested in.

Of course, if you can do better, that would be fantastic.

**Comment by mjakubowski84** [comment]
Please check #135! If that is fine then we collect changes (including schema name change) and do the release. That would be 1.1 and my 1.1 branch will become 1.2 :)

**Comment by mac01021** [comment]
This looks like it will meet my needs. I can test it when I get home
tonight.


Some of the other mutable.Buffer operations like remove, etc might be nice,
but they are not required for my current use case.  I think I can just use
the existing add(string, value) method to add new columns or list elements,
but it might be less than totally intuitive for the latter.

**Comment by mjakubowski84** [comment]
Released in 1.1.0
