### ISSUE TITLE
Include TypedSchemaDef, etc, for byte arrays.

### ISSUE THREAD

**Issue by mac01021** [mjakubowski84/parquet4s#138]
so that, by default, `Array[Byte]` is encoded as `BINARY` rather than a repeated byte column.

**Comment by mjakubowski84** [comment]
As for workaround I recommend using `ByteBuffer` in place of `Array[Byte]` and using custom codec and schema def. Writing default implementation for `Array[Byte]` can be tricky.

**Comment by mac01021** [comment]
I wrote. A custom implementation for Array[Byte] last night and it seems to
work. What's the tricky part? I wonder if I have a bug.

**Comment by mjakubowski84** [comment]
I guess there's nothing tricky if you have a specific implementation for `Array[Byte]`. I mean that it is problematic to have both specific implementation and generic implementation (any C[X]) in the same default scope. And make it work in every Scala version. That's why at this moment Parquet4S doesn't have it. I may have a solution for this already but it needs thorough testing.
