### ISSUE TITLE
Implicit evidence exception with custom case class 

### ISSUE THREAD

**Issue by osleonard** [mjakubowski84/parquet4s#146]
Hello , I am trying out this lib to replace spark however I noticed below after defining case class and schema I  get ```could not find implicit value for evidence parameter of type com.github.mjakubowski84.parquet4s.ParquetWriter.ParquetWriterFactory[com.example.Information]``` at compile time

case class Information(
    version: Int,
    processUuid: UUID,
    tracingUuid: UUID, // base
    countryCode: Option[String],
    time: Long,
    visibility: Boolean,
    requestCode: String,
    errorCode: String,
    detailedError: Option[Either[String, Array[Byte]]] // detailed error
)

Message in the sink is of type 

  final case class Message(
      msg: Information,
      offset: ConsumerMessage.CommittableOffset
  )
// message sink

  def messageSink(
      writePath: String,
      writeWindow: FiniteDuration,
      topic: String,
      committerSettings: CommitterSettings
  ): Sink[Message, Future[Done]] =
    ParquetStreams.toParquetIndefinite(
      path                 = writePath,
      maxChunkSize         = writerOptions.rowGroupSize,
      chunkWriteTimeWindow = writeWindow,
      buildChunkPath       = chunkPath(topic),
      preWriteTransformation = { message: Message =>
        message.msg
      },
      postWriteSink = committableSink(committerSettings),
      options       = writerOptions
    )

any ideas what could be wrong

**Comment by mjakubowski84** [comment]
Hi!
The reason is the same as this schema would fail for you in Spark. You need
to create a custom codec for java.util.Uuid. Check readme and examples for
more details. Oh, and you also use Either of String and array of bytes.
Probably you want to split it into two separate columns.
Cheers!

niedz., 28 cze 2020, 20:05 użytkownik Akinmolayan Olushola <
notifications@github.com> napisał:
