### ISSUE TITLE
Reading only subset of columns

### ISSUE THREAD

**Issue by lake4790k** [mjakubowski84/parquet4s#158]
When I read `RowParquetRecord`s all the columns in the parquet file are populated in the map. If I only want to read a small subset of columns is it possible to gain performance by using a case class with only those fields I want to read or will that still read all the data in the parquet file to build the small case class?

**Comment by mjakubowski84** [comment]
Hi!
Unfortunately, this is not supported out of the box by official parquet-hadoop library that Parquet4S uses underneath. Maybe it can be achieved by overriding schema here: https://github.com/mjakubowski84/parquet4s/blob/master/core/src/main/scala/com/github/mjakubowski84/parquet4s/ParquetReadSupport.scala#L14. If we (optionally) provide here own schema instead of one that comes here from file metadata then maybe it will work. But it has to be proved.

**Comment by lake4790k** [comment]
Thank you for the clarification, I'm leaving this issue open as could be interesting in the future.
