### ISSUE TITLE
getting the maximum or minimum of a column

### ISSUE THREAD

**Issue by kozy** [mjakubowski84/parquet4s#165]
Hi, thanks for such a nice library.

I want to read the lowest and highest value of a column in a partitioned data set. Is there an easy way to access the statistics?

Thanks!

**Comment by mjakubowski84** [comment]
Hi!
Unfortunately Parquet4S neither has Aggregation API nor exposes aggregated statistics. I have some plans for introducing some Statistics API but it won't happen any time soon.

In order to get the maximum value of some column using parquet-hadoop (the official Apache library that Parquet4S is based on) you either can compute that while running the filter (that would be approach of Aggregation API) or you can process statistics of each row group. The latter is what you are asking for. You should be able achieve that in a pretty easy way by walking through your partitioned directory using hadoop client and reading row groups of each file using https://github.com/apache/parquet-mr/blob/master/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileReader.java. 
Some snippet to make your investigation easier : ParquetFileReader.open(org.apache.parquet.hadoop.util.HadoopInputFile).getRowGroups.fold(0) { case (max, rowGroup) => rowGroup.getColumns.find(...).head.getStatistics.getGenericMax [...] }

**Comment by mjakubowski84** [comment]
Of course you can also just read the whole dataset and call _.minBy on the collection :)

**Comment by kozy** [comment]
Thank you. Thinking about it, I like your latter solution, nice and simple and it can be replicated for similar queries, but I am afraid it might be  slow for my use. Is there a way to only read a single column? Also looking into maybe Flink or Spark, it seems I can use sql there, which might be optimized to use select min/max()

**Comment by mjakubowski84** [comment]
Flink and Spark scale by distributing an app on the cluster. If you're fine with the costs of the infrastructure then both are a good option.
The goal of using this library is to handle Parquet files when you actually do not need to run the cluster.
I do not know what is your use case but do not worry of performance so much. Hadoop will not read the whole file in order to find min or max. It will just check the footer of each block, you will process only column metadata. Rest of the file content is skipped.

**Comment by kozy** [comment]
Yes, and I like the simplicity of this library. I probably do not need anything more. The case is to subscribe to a stream of sequential data. The stream does not wait for me and when a network error happens I want to quickly fetch some missing items elsewhere, and then proceed in the were I left off. 

Come to think of it, I can probably make something which just inspects the last item I posted in the topic. I skipped that because I noticed that when the stream broke, the ParquetWriter did not write what it had until then. Maybe the exception cause the Akka stream to not properly stop. I will look into that and maybe open another ticket if needed. 

Thank you Marcin, for your help!

**Comment by mjakubowski84** [comment]
Regarding Stream not stopping properly in case of exception - if you mean `viaParquet` you made me think about that and I notice that I didn't override `onUpstreamFailed` and it doesn't close file writers. Because of that, in your case, some writes could have been not flushed. So please create an issue for that.

And I though a little bit about other possible easy ways for reading min/max from your dataset. If you store your data in AWS S3 then probably the easiest way is to query it with Athena. You can use AWS SDK or Athens'a JDBC driver to run simple SQL query. There's also Presto (actually Athena is Presto under the hood), Drill, Impala, Hive. Or BiqQuery in Google Cloud. Whatever you have running in your cloud.

**Comment by mjakubowski84** [comment]
You may also have a look at https://doc.akka.io/docs/akka/current/stream/stream-error.html#delayed-restarts-with-a-backoff-operator and https://doc.akka.io/docs/akka/current/stream/stream-error.html#supervision-strategies so that you avoid stream to be die in case of temporary network issue.

**Comment by mjakubowski84** [comment]
@kozy check out https://github.com/mjakubowski84/parquet4s/releases/tag/v1.5.1

**Comment by kozy** [comment]
Still not gotten around testing it (weekend project). Just wanted to let you know I really appreciate the guidance and bugfix. Hope to test it soon. Thank you!
