### ISSUE TITLE
Optionally rotate each file in viaParquet independently

### ISSUE THREAD

**Issue by mjakubowski84** [mjakubowski84/parquet4s#168]
Currently viaParquet in akka and fs2 module rotate all files when maxDuration expires or (global) maxCount is reached. As this is good compromise between functionality and resource utilisation it may result in (during partitioning) having much smaller files than expected. ViaParquet can optionally start schedulers for each started file and keep count per each. While this approach will eat more resources (depending on number of partitions) it will optimise files for further reads.

**Comment by sndnv** [comment]
I think this is an issue we've been facing lately or, at least, it's contributing to some performance degradation we are observing; basically, there are lot of messages going to Parquet on S3 (100K+ per second) but rather than large files with lots of messages, we end up with tiny ones that barely have anything in them.

For example, we have configured rotation to trigger either every hour or every 1M messages but we end up with files that span 1-2 minutes with a few hundred messages in them.

My question is, is this planned to be fixed in `2.0.x`? If not, would it be OK to extend the [existing writer tracking](https://github.com/mjakubowski84/parquet4s/blob/master/akka/src/main/scala/com/github/mjakubowski84/parquet4s/ParquetPartitioningFlow.scala#L167) to include counters for individual files. The time-based rotation should also take into account individual files (and when they were last rotated) but I don't have a solution right now.

**Comment by mjakubowski84** [comment]
Yes, I am aware of this issue but it will not be addressed immediately with the new release. This was supposed to be a next goal after as release 2.x focus on many overall performance of the library, dependency upgrades and API improvements.

**Comment by mjakubowski84** [comment]
But I welcome any contribution :)

**Comment by mjakubowski84** [comment]
@sndnv There is yet another issue that may be the reason of your problem. `viaParquet` rotates files when `maxCount` is reached AND independently when `maxDuration` is reached. So, it is probable that rotation can happen quickly one after another. In order to fix it, the timer should be cancelled during rotation and instead `schedulePeriodically` `scheduleOnce` should be used.
That is easy to achieve with Akka, but more difficult in case of FS2 with the current design.

**Comment by sndnv** [comment]
Thanks for the update :) I've been unable to look into this recently but I'll try to get a PR going in the coming days.

**Comment by sndnv** [comment]
I have no experience with FS2 so I don't even know how to resolve the individual timer issue; I would rather leave it to someone that actually knows what they are doing 😅

**Comment by sndnv** [comment]
I ran some basic tests today and things seem to be working; can't tell yet if the performance has improved but at least it looks like nothing was broken.

**Comment by mjakubowski84** [comment]
Cool, I addressed FS2 already. I need to add a small change to Akka flow for consistency and then I will release next RC version. That will be a last one before final release.

**Comment by mjakubowski84** [comment]
@sndnv Final release of 2.0.0 is there!
