### ISSUE TITLE
Making particular String field required to be non-null

### ISSUE THREAD

**Issue by vreuter** [mjakubowski84/parquet4s#246]
Hello, many thanks for effort to develop and maintain this library! I'm just starting to use it and it seems great.

I have a `case class` with many fields, and inference of the data types for the Parquet schema works perfectly, just using `ParquetWriter.of[MyType]...`. with some fields typed as `Option` and others not (e.g., just `String` or `Double`).

However, it seems that `String`, even if not wrapped in `Option` in the case class definition, is not inferred as restricted to be non-null, the way that `Int` and `Double` are. Am I missing something? __If not, is there an easy way I could tell the writer about the particular `String` field that is required to be non-null__? I looked around the docs and repository and didn't find one, but sorry if I overlooked.

**Comment by mjakubowski84** [comment]
Hi @vreuter.
String is treated as optional field, as, unlike Int or Double, Scala allows null to be assigned ot it. In order to change it you can provide custom schema definition for String or you can create own type, e.g. RequiredString for particular text types. Check documentation: https://mjakubowski84.github.io/parquet4s/docs/records_and_schema/#custom-types

**Comment by vreuter** [comment]
Cool, many thanks @mjakubowski84 !
