### ISSUE TITLE
Creating a `TypedSchemaDef` for a case class (used with template parameters)

### ISSUE THREAD

**Issue by akauppi** [mjakubowski84/parquet4s#255]
I've read the documentation, but don't quite understand how to make the implicit `TypedSchemaDef` for my own case classes. I have a bunch of them - one here for study.

```
case class Chain(
  name: String,
  code: String,
  country: Option[Country_ISO_3166],   // Enumeratum
  created_at: LocalDateTime
)
```

The error I get is:

```
Cannot write data of type T. Please check if there is implicit TypedSchemaDef available for each field and subfield of T.
```

Writing:

```
  def pqtSingle[T](g: Gulpable[T]) (implicit as: ActorSystem): Future[Done] = {
    val pp: ParquetPath = pqtFilename(g)
    val src: Source[T,_] = RunDim.source(g)

    src.runWith(
      ParquetStreams.toParquetSingleFile.of[T]
        .options(pqtWriteOptions)
        .write( pp )
    )
  }
```

I am in charge of both (the case class and the writing), so can provide extra class support, once I understand what is needed.

On JSON encoding/decoding (with Circe), such cases are handled by adding a one-liner that creates the necessary conversions for the case classes I wish to tackle.

**Comment by mjakubowski84** [comment]
As error message says Parquet4s fails to encode your case class. Please read documentation which types are supported out of the box. And please refer to the documentation how to write own codecs for custom types.

Hint: that's enumeratum type, I presume

**Comment by akauppi** [comment]
I created a [repo](https://github.com/akauppi/parquet4s-gym) to narrow down on the problems faced. Some I've been able to solve (links below). 

- [x] Custom encoder for strings

   This [sample](https://github.com/mjakubowski84/parquet4s/blob/master/examples/src/main/scala/com/github/mjakubowski84/parquet4s/CustomType.scala) shows the way. Use `BinaryValue`. ( Docs show `IntValue`; there is no `StringValue`. )

- [ ] Encoder for a case class that uses custom encoder for one of the fields

   This remains unsolved. I would like not to create brand new custom encoders but have the "system" find the encoders of the components. 

   Described in [Problem 1](https://github.com/akauppi/parquet4s-gym/blob/master/PROBLEM.1.md)

**Comment by mjakubowski84** [comment]
1. I do not own Enumeratum so I do not (and rather I will not) provide codecs for it. Enumeratum provides its own (optional afaiu) codecs for Circe that's why they work for you when you import https://github.com/lloydmeta/enumeratum/tree/master/enumeratum-circe.
2. Usually you would place type classes (here codecs and schema defs) to companion object of given type. So it would be best to have generic Enumeratum type classes in companion object of `EnumEntry`. As you also do not own Enumeratum then you can:
  * Create yet another base Enum trait as in https://github.com/akauppi/parquet4s-gym/pull/1/files and use it for all your enums. Place generic codec and schema def in companion object of that base trait.
  * Just use specific type classes for your enums
3. Still, you found an interesting bug. As long as you use specific type classes all is fine. But when you define them in local scope - as you did in your repo - implicit scoping go mad and type class for string and for collecton + Char clash. I will work on it in the next release to solve it. Thanks for the info and code for replication.

**Comment by akauppi** [comment]
Handling enums hasn't been the main problem, and I have a [solution](https://github.com/akauppi/parquet4s-gym/blob/master/src/main/scala/Main.scala#L145-L154) for that.

<details><summary>copy of the solution</summary>
<pre>
implicit def enc[T <: EnumEntry]: ValueEncoder[T] =
    (data: T, _: ValueCodecConfiguration) => BinaryValue( data.entryName )

implicit def schema[T <: EnumEntry]: TypedSchemaDef[T] =
  SchemaDef.primitive(
    PrimitiveType.PrimitiveTypeName.BINARY,
    Some( StringLogicalTypeAnnotation ),
    required = true
  )
  .typed
}
</pre>
</details>

The real problem - now described in [Problem #2](https://github.com/akauppi/parquet4s-gym/blob/next/PROBLEM.2.md) - is having a central function for writing N case classes, to Parquet. Since I have many data types (50+), I would like to define them separately and the code would be getting 1..n of them, for writing.

I still haven't found a suitable solution to this - or cannot even claim to understand the problem, properly.

**Comment by akauppi** [comment]
Got it solved. The problem was more in the way I was testing the library, than in my actual use needs.

```
def write[T : ParquetSchemaResolver : ParquetRecordEncoder](ts: Seq[T], pPath: ParquetPath)(implicit as: ActorSystem): Future[_] = { ...
```

The type guards make sure that anything getting inside `write` can also be written out.
