### ISSUE TITLE
Decoding of timestamp fields generated by pandas/pyarrow

### ISSUE THREAD

**Issue by Yanikovic** [mjakubowski84/parquet4s#277]
Hey!

I have generated a simple pandas dataframe that has a schema like this:
```
timestamp    datetime64[ns]
count                 int64

timestamp           | count
2009-01-01 00:00:00 | 15991
2009-01-01 01:00:00 | 17148
2009-01-01 02:00:00 | 15659
2009-01-01 03:00:00 | 13346
2009-01-01 04:00:00 | 9643
```

Then I store this dataframe as a parquet file like this:
`df.to_parquet("taxi-counts.parquet")`

Finally, I try to read this file in Scala using parquet4s like this:
```
case class DataPoint(timestamp: java.sql.Timestamp, count: Long)

ParquetReader
  .as[DataPoint]
  .read(Path("taxi-counts.parquet"))
  .foreach(println)
```

However, I get this error:
```
Exception in thread "main" com.github.mjakubowski84.parquet4s.ParquetRecordDecoder$DecodingException: Failed to decode field timestamp of record: RowParquetRecord(timestamp=LongValue(1230768000000),count=LongValue(15991))
```

I am not sure why this should be difficult to decode, since it is just a datetime64 type of pandas that should be able to be converted to a standard `java.sql.Timestamp`.

**Comment by mjakubowski84** [comment]
Hi!

Parquet4s treats timestamps as INT96 (stored as a binary), because Timestamp is date (Int) + time in nanos (Long). Datetime64 is less precise. However, it doesn't mean that Parquet4s shouldn't be able to read such data.

Can you share a link to a sample file with datetime64 column, including BC & AD, with millis and without. It will help to implement the improvement faster :)

Thanks

**Comment by mbykovskyy** [comment]
INT96 has been deprecated (https://issues.apache.org/jira/browse/PARQUET-323), so many tools are now using INT64 to represent timestamps.

I ran into the same issue because my parquet file was generated by PyArrow, but was able to workaround it by forcing the INT96 type during parquet file generation.

**Comment by mjakubowski84** [comment]
That is a fair point with INT64. Parquet4s should support it as a timestamp format both in reads and writes (as an option). Spark, Hive and Impala highly influenced the library. Even now, they all use INT96 for timestamps, at least by default. 

I am going to prioritise the work on this issue. @Yanikovic @mbykovskyy If you do not want to wait, you can write a custom decoder typeclass and transform `LongValue` to a timestamp.

**Comment by mjakubowski84** [comment]
Out of the box typeclasses are released with https://github.com/mjakubowski84/parquet4s/releases/tag/v2.7.0
