### ISSUE TITLE
Unsure how to use for 'semiauto' approach

### ISSUE THREAD

**Issue by stacycurl** [mjakubowski84/parquet4s#327]
Hello, I want to use parquet4s with a custom encoders/decoders for BigDecimal, but still leverage the record encoders/decoders that are derived.

As a first step towards that I have

```scala
case class Adt(bigDecimal: BigDecimal)

object Adt {
  implicit val adtParquetRecordDecoder: ParquetRecordDecoder[Adt] =
    ??? // not sure what goes here, ParquetRecordDecoder.genericDecoder requires Adt plus the shapeless LabelledGeneric.Repr type for Adt
}
```

Is there a way to derive a decoder (and encoder) by only specifying the type I want ?

**Comment by stacycurl** [comment]
I've been shown the light:

```scala
  implicit class LabelledGenericSyntax[A, R](private val self: LabelledGeneric.Aux[A, R]) extends AnyVal {
    def summonParquetRecordDecoder(implicit reprDecoder: Lazy[ParquetRecordDecoder[R]]): ParquetRecordDecoder[A] =
      ParquetRecordDecoder.genericDecoder[A, R](self, reprDecoder)
  }
  
  LabelledGeneric[Adt].summonParquetRecordDecoder
```

Would still be nice to have a semiauto method in this library though.

**Comment by mjakubowski84** [comment]
Hi @stacycurl.
Sorry for the very late response. 
In order to provide your own codec and/or schema for BigDecimal, it is enough to provide your type class of codec and/or schema def for it. Just put the type class in the overriding implicit scope. Please refer to the documentation and examples: https://mjakubowski84.github.io/parquet4s/docs/records_and_schema/#custom-types and https://github.com/mjakubowski84/parquet4s/blob/master/examples/src/main/scala/com/github/mjakubowski84/parquet4s/core/WriteAndReadCustomTypeApp.scala
