### ISSUE TITLE
Add support for java.time.LocalDate and java.time.LocalDateTime

### ISSUE THREAD

**Issue by moonkev** [mjakubowski84/parquet4s#68]
Hello @mjakubowski84 

First let me say that this is a wonderful project.  I've been hoping for something like this for quite a while now, so many thanks for this!  I am raising this issue as most often we are working with the Java 8 date/time API.   It is often times difficult to work with the java.sql versions, and much conversion is done on our side to accommodate using them in our case classes which will be used with parquet4s.   My proposal would be to support both the java.sql date/time classes as well as the java.time classes. 

Also, we have even run into issues when rendering certain timestamps in an Impala table that we will see a UTC midnight instead representing the previous day, but with 24:00 as the time (I'm guessing this has to do with the day and actual epoch being encoded separately in parquet - but I'm not too familiar with exactly how timestamps are encoded in parquet).  So essentially, they represent the same instant but are rendered differently.  However, I think this is more due to #21 than the data type.  

I have made the following commit on my fork that adds support for the java.time API as well as makes the timezone on TimeValueCodecs configurable (that was really the best way I could think of to make it configurable.  Was thinking of a system property, but that makes testing a little off, and locks you in for the lifetime of your application).  I have also updated test cases to account for these changes.  The commit can be found [here](https://github.com/moonkev/parquet4s/commit/9e032602be53932463f6cf5bda52aed94dc7a347)

Please let me know if this commit looks suitable to you and I will raise a pull request.  Also, if there are any changes that you would like me to make to this, I am more than happy to implement them.

**Comment by mjakubowski84** [comment]
Hi @moonkev,

I am ver happy that you appreciate my effort! It incites me even more to make this project better and more mature.

I like your idea, especially because one of the goals of this project is to give flexibility to developers to use various data types according to their needs.

I checked your commit. Changes in the TimeValueCodecs look fine! However, I have small doubts about how you handle the TimeZone setting. I didn't think much about the solution when I created #21. Having mutable variable in object of TimeValueCodecs indeed seems as the easiest solution and for sure it is better than what is now. Unfortunately, it still makes impossible for reading different types with different time zone in parallel. And I am not a big fun of global-like mutable variables. 
What do you think about having time zone as an optional setting for reader and writer? Writer already has `Options` parameter. We can add similar one to the reader. Writer and reader can translate it to implicit variable `TimeZoneFor[T]` and TimeValueCodecs can use it. May sound as over-engineering, still, the whole project is based on type classes so it would be consistent. I am open to your suggestions!

**Comment by moonkev** [comment]
I think that definitely makes sense.  I have removed the timezone change and squashed down the commit [here](https://github.com/moonkev/parquet4s/commit/6d691fa4fb092298b9a413b9bcbd95ae452085d9) so now it only contains the change to add the Java 8 date/time API types.  If this looks good to you I can create a pull request and we can bring the timezone discussion back into your original ticket #21

**Comment by mjakubowski84** [comment]
Yes, please do so!

wt., 19 lut 2019, 21:51: Kevin Mooney <notifications@github.com> napisał(a):

**Comment by moonkev** [comment]
Thank you, I have opened the above reference PR.

**Comment by mjakubowski84** [comment]
Your PR is merged!
I just noticed that CircleCI was disabled for forked PRs. It should work for next ones from now.
Please tell me how soon you want have your changes released. Do you want to handle #21 first? I can have a look at it myself today evening (CET, speaking about time zones...).

**Comment by moonkev** [comment]
Thank you. If you are willing to look at #21 that would be great.  I wouldn't mind helping on it, but it seems you have a concrete idea on how you would like to implement it (which sounds good by the way).  So I'm in no hurry for the release, I can wait for this change as well as #21 as your time permits.  Also, I would be glad to help with any testing needed for that item.  Thank you again!

**Comment by mjakubowski84** [comment]
OK, so I am closing this issue, thanks for contributing! I will ask you for checking #21 when I am ready
