### ISSUE TITLE
Prove application of parquet4s-akka in infinite streaming

### ISSUE THREAD

**Issue by mjakubowski84** [mjakubowski84/parquet4s#71]
- build an example app (e.g. with Kafka)
 - check possible improvements e.g. timer/tick-based file flushing, path factory/function

**Comment by moonkev** [comment]
Hi @mjakubowski84 

Just saw this issue and wanted to actually provide a little input as we are using parquet4s at my work now with infinite streams.  We actually have both of the features that you mention above.  I just created our own sink easily enough instead of using the ones from the parquet4s akka artifact.  For the timer/tick-based flushing, I simply use the groupedWithin artifact.  So this allows to both provide a maximum threshold of elements or a finite duration (whichever comes first) that is used to flush.  The sink also takes in a function that is used to derive the path.  

The one tricky part is if you want to shutdown the app, but still have elements in the groupedWithin operators queue.  For that part, I tack on a killswitch to the stream.  I then have a function that takes in a killswitch and a variable argument of futures.  This function adds a shutdown hook that executes the shutdown method of the killswitch then awaits any futures that you pass in to the varargs.  For the futures passed in, these would ideally be a future that is materialized from your sink. With my sink, it just falls into a Sink.ignore, so I get back the Future[Done] materialized value - so I pass this into to my shutdown hook registering function to await the completion of the sink.

This obviously won't help you if you have messages in the groupedWIthin operator's queue and your application completely falls over for some reason - such as host failure.  However, I don't think there is much you can do in that case anyhow.  If you are interested in any of this let me know and I can show some code examples, and happy to help implement or test wherever if you think any of it fits your vision for parquet4s.

**Comment by mjakubowski84** [comment]
Hi @moonkev 
Thanks for your input. I will definitely take a look at groupedWithin. 
Regarding your issue with messages left in stream during shutdown/critical fail I can give you one hint. If you are feeding your stream with messages from Kafka, Rabbit or other queue it is a good practice to ack a message as late as possible in the stream (at the very end preferably). Taking that approach you are sure that you will not lose the data. However, you have to make sure that your stream is idempotent in order to handle the restarts properly. In case of saving data to a file it is hardly possible to assure idempotency so you have to decide on your own whether you wish to ack the message just before saving, in parallel to it or after - depending what suits you best.

**Comment by moonkev** [comment]
These are very good points @mjakubowski84 .  We do have a couple streams where the source doesn't have any sort of bookmarking / transactional history, and thus no acknowledgment interface. Another dilemma could arise if batch size/tick are rather large, and the upstream source will no longer emit without a proper ack. Although a possible solution to this second scenario is to maybe use akka persistence to cache a batch of messages inline, and then ack to the persistent actor to flush the persistent cache after writing.
